include:
  - project: platform/promotion
    ref: task/default-run-security-scans
    file: ci/security.yml

stages:
  - "🧪 security-test"

sonar_scan:
  stage: "🧪 security-test"
  extends: .sonar_scan
  script:
    - |
      sonar-scanner \
        -Dsonar.analysis.mode="publish" \
        -Dsonar.projectName="${CI_PROJECT_PATH}" \
        -Dsonar.projectKey="${CI_PROJECT_PATH_SLUG}" \
        -Dsonar.links.ci="${CI_PROJECT_URL}/pipelines" \
        -Dsonar.links.issue="${CI_PROJECT_URL}/issues" \
        -Dsonar.gitlab.project_id="${CI_PROJECT_ID}" \
        -Dsonar.gitlab.commit_sha="${CI_COMMIT_SHA}" \
        -Dsonar.gitlab.ref_name="${CI_COMMIT_REF_NAME}"
  allow_failure: true
